[package]
name = "meowc-check"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
meowc-check-core = { path = "../meowc-check-core" }
